/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddExerciseDialog: typeof import('./src/components/AddExerciseDialog.vue')['default']
    Bar: typeof import('./src/components/today/Bar.vue')['default']
    Bars: typeof import('./src/components/today/Bars.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ConfirmWeightSetupDialog: typeof import('./src/components/ConfirmWeightSetupDialog.vue')['default']
    CreateFoodDialog: typeof import('./src/components/CreateFoodDialog.vue')['default']
    EditLogDialog: typeof import('./src/components/today/EditLogDialog.vue')['default']
    ExerciseListView: typeof import('./src/components/liveworkout/ExerciseListView.vue')['default']
    ExerciseLoggingView: typeof import('./src/components/liveworkout/ExerciseLoggingView.vue')['default']
    FoodDisplay: typeof import('./src/components/FoodDisplay.vue')['default']
    Gym: typeof import('./src/components/today/Gym.vue')['default']
    GymCard: typeof import('./src/components/today/GymCard.vue')['default']
    GymDate: typeof import('./src/components/GymDate.vue')['default']
    LiveExerciseCard: typeof import('./src/components/LiveExerciseCard.vue')['default']
    LogEditedDialog: typeof import('./src/components/today/LogEditedDialog.vue')['default']
    LogExerciseDialog: typeof import('./src/components/today/LogExerciseDialog.vue')['default']
    LogOtherMealDialog: typeof import('./src/components/LogOtherMealDialog.vue')['default']
    Meal: typeof import('./src/components/today/Meal.vue')['default']
    MealCard: typeof import('./src/components/today/MealCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchList: typeof import('./src/components/SearchList.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SimpleMacros: typeof import('./src/components/SimpleMacros.vue')['default']
    TodayGym: typeof import('./src/components/TodayGym.vue')['default']
    TodayMeal: typeof import('./src/components/TodayMeal.vue')['default']
  }
}
